### PR TITLE
Rewrite stats CSS (Assembly #1105)

### PR DESCRIPTION
**Pull request by lachlanjc**

### CODE REVIEW

**Comment by chrislloyd** [comment]
:+1:

**Comment by lachlanjc** [comment]
@chrislloyd Merge?

**Comment by chrislloyd** [comment]
We're trying a format of one ":+1:" and somebody else merging the PR to ensure that 2 people have eyes on external PRs.

**Comment by lachlanjc** [comment]
@chrislloyd Sure thing!

**Comment by lachlanjc** [comment]
@whatupdave 👍👊

**Pull request merged**
