### PR TITLE
Redesign Guides

### PR DESCRIPTION
**Pull request by lachlanjc**
- Removes breadcrumbs CSS from Bootstrap + components
- Redesigns guides
- Cleans up markup

New Guides UI

### CODE REVIEW

**Comment by lachlanjc** [comment]
Sorry, I just realized this messes up the FAQs page. I'll fix this later once I have my computer, but don't merge it just yet.

**Comment by lachlanjc** [comment]
@chrislloyd I've gotten it set up so that both FAQs and Guides go to the same view, and only show what they need. However, the code isn't so fantastic — any tips on cleaning it up?

*Besides CQ, this is ready for review + merge.*

**Comment by whatupdave** [comment]
Hey @lachlanjc this is great stuff. It's definitely in line with the card style of Assembly, but I think for the guides, which contains a large amount of text it might be better to keep the white background. If you have another stab at this feel free to reopen or create a new PR.

**Comment by lachlanjc** [comment]
@whatupdave @chrislloyd Just fixed this up with a new, white background. Thoughts?

**Comment by lachlanjc** [comment]
(I also fixed the merge conflicts)

**Pull request closed without merging**
