### PR TITLE
Remove owl tweet carousel

### PR DESCRIPTION
**Pull request by lachlanjc**
Having a whole library just for displaying a few tweets on one page is way too much baggage. I pared the tweets down to just two as well.

### CODE REVIEW

**Comment by whatupdave** [comment]
Looks good! Can you fix the tweets for small sizes?

screen shot 2015-04-11 at 1 39 46 pm

**Comment by lachlanjc** [comment]
@whatupdave And three characters later...ta-dah!

**Comment by pletcher** [comment]
LGTM - :+1:

**Comment by lachlanjc** [comment]
Merge?






On Saturday, Apr 11, 2015 at 21:08, Charles Pletcher <notifications@github.com>, wrote:

LGTM -

**Pull request merged**
