### PR TITLE
Refactor markup on new idea page

### PR DESCRIPTION
**Pull request by lachlanjc**

### CODE REVIEW

**Comment by chrislloyd** [comment]
This is a :-1: from me. The `<Tile>` component is used pretty widely around the site and is really important for reusability. It adds some extra markup like a slightly different border color too.

**Comment by lachlanjc** [comment]
@chrislloyd Ah yep, I'm going to make a more reusable `<Tile>` that's integrated with the grid. I can fix it when I get home.

**Comment by chrislloyd** [comment]
Hrrm, that makes me nervous too. `<Tile />` is very very simple and doesn't need much more extension. I'm not as worried about adding more markup to the page as I am about creating easily re-usable components.

**Comment by lachlanjc** [comment]
@chrislloyd Agreed. I just mean a `<Sheet>` or something that has one consistent grid width and a `<Tile>` inside. Is that bad?

**Comment by chrislloyd** [comment]
Hard for me to comment without seeing what you plan on implementing.

**Comment by lachlanjc** [comment]
@chrislloyd I just pushed up the `<Sheet />`. What do you think?

**Comment by whatupdave** [comment]
Ping @chrislloyd

**Comment by lachlanjc** [comment]
<small>PONG 😄</small>

**Comment by chrislloyd** [comment]
Hey @lachlanjc I think this might just be moving complexity around for the sake of it. A couple of things:

* I don't really see that padding is something intrinsic to a `<Tile />`
* `<Sheet />` doesn't seem useful from a UX perspective. I'm not entirely sure when I'd use a sheet over something else (like just a plain ol' `Tile`). 
* I don't think the one usage of this pattern is enough to justify making it a separate component. I think I'd prefer to see it established as a common pattern around the site (used in multiple places) before extracting it.

I'm closing this for the moment because I'm not sure there's too much to do here. Feel free to let me know if I'm missing something.

**Comment by lachlanjc** [comment]
@chrislloyd Good points.

- The purpose of `<Sheet />` is to keep a consistent size for cards on pages across the site, and let us change that in the future if we feel the need for it. I’m using `<Tile />` inside, as you said, for reusability.
- However, I definitely wouldn’t being making Sheet if it was just for this page. I’m thinking that in the future we can use it for other pages as well, but this PR was just for Ideas, so I didn’t expand the scope of it.
- We could remove the padding; should we just have a container div that has margin or padding per-use on every page?

**Pull request closed without merging**
