### PR TITLE
Clean up "getting started with bounties" markup

### PR DESCRIPTION
**Pull request by lachlanjc**

### CODE REVIEW

**Comment by chrislloyd** [comment]
Travis is erroring out but this looks :+1: to merge once it's working again.

**Comment by lachlanjc** [comment]
I'm getting a 404 from Travis @chrislloyd

**Comment by chrislloyd** [comment]
Yeah it's a Travis Pro instance — there seems to be an issue with Travis with the change to OSS. Looking into it.

**Comment by lachlanjc** [comment]
@chrislloyd Seen anything?

**Comment by chrislloyd** [comment]
@lachlanjc Just awesomeness!

**Comment by lachlanjc** [comment]
☺️

**Comment by lachlanjc** [comment]
Do you guys have auto-deploys from GH? Or is it just manual to Heroku?

**Comment by chrislloyd** [comment]
Auto-deploy. If the tests pass it should be up in production soon.

**Comment by lachlanjc** [comment]
@chrislloyd 👍

**Pull request merged**
